import {
  AppCommandDescriptor as AppCommandDescriptorSchema,
  AppCommandId as AppCommandIdSchema,
  PROJECT_CUSTOM_ACTION_ICON_IDS,
  type AppCommandDescriptor,
  type AppControlRisk,
} from "@t3tools/contracts";

import type { AppCommandDomain } from "./registry.ts";

export interface AppCommandCatalogEntry {
  readonly id: string;
  readonly descriptor: AppCommandDescriptor;
  readonly domain: AppCommandDomain;
}

const emptyInput = {
  type: "object",
  properties: {},
  additionalProperties: false,
} as const;
const openInput = { type: "object", additionalProperties: true } as const;
const openOutput = {} as const;

const stringProperty = { type: "string" } as const;
const booleanProperty = { type: "boolean" } as const;
const integerProperty = { type: "integer", minimum: 0 } as const;
const objectInput = (
  properties: Readonly<Record<string, unknown>>,
  required: ReadonlyArray<string> = [],
) =>
  ({
    type: "object",
    properties,
    ...(required.length > 0 ? { required } : {}),
    additionalProperties: false,
  }) as const;

const command = <const Id extends string>(
  id: Id,
  domain: AppCommandDomain,
  owner: AppCommandDescriptor["owner"],
  risk: AppControlRisk,
  title: string,
  requiredGrant: string | null = null,
  inputSchema: Readonly<Record<string, unknown>> = openInput,
): AppCommandCatalogEntry & {
  readonly id: Id;
  readonly descriptor: AppCommandDescriptor & { readonly id: Id };
} => {
  const descriptor = AppCommandDescriptorSchema.make({
    id: AppCommandIdSchema.make(id) as AppCommandDescriptor["id"] & Id,
    version: 1,
    owner,
    title,
    description: `${title} through T3's semantic command surface.`,
    domain,
    risk,
    requiredGrant,
    inputSchema,
    outputSchema: openOutput,
  });
  return {
    id,
    domain,
    descriptor: descriptor as AppCommandDescriptor & { readonly id: Id },
  };
};

export const APP_COMMAND_CATALOG = [
  command(
    "ui.project.select",
    "ui",
    "client",
    "navigate",
    "Select project",
    null,
    objectInput({ projectId: stringProperty }, ["projectId"]),
  ),
  command(
    "ui.thread.select",
    "ui",
    "client",
    "navigate",
    "Select thread",
    null,
    objectInput({ threadId: stringProperty }, ["threadId"]),
  ),
  command("ui.sidebar.toggle", "ui", "client", "navigate", "Toggle sidebar", null, emptyInput),
  command(
    "quick-chat.open",
    "ui",
    "client",
    "navigate",
    "Open quick chat",
    null,
    objectInput({ threadId: stringProperty }),
  ),
  command("quick-chat.close", "ui", "client", "navigate", "Close quick chat", null, emptyInput),
  command("quick-chat.focus", "ui", "client", "navigate", "Focus quick chat", null, emptyInput),
  command("quick-chat.toggle", "ui", "client", "navigate", "Toggle quick chat", null, emptyInput),
  command(
    "ui.palette.open",
    "ui",
    "client",
    "navigate",
    "Open command palette",
    null,
    objectInput({ open: { type: "string", enum: ["add-project", "new-thread-in"] } }),
  ),
  command(
    "ui.palette.close",
    "ui",
    "client",
    "navigate",
    "Close command palette",
    null,
    emptyInput,
  ),
  command(
    "ui.palette.toggle",
    "ui",
    "client",
    "navigate",
    "Toggle command palette",
    null,
    emptyInput,
  ),
  command("ui.composer.focus", "ui", "client", "navigate", "Focus composer", null, emptyInput),
  command(
    "ui.composer.stash",
    "ui",
    "client",
    "mutate",
    "Stash composer",
    "thread:mutate",
    emptyInput,
  ),
  command("ui.diff.open", "ui", "client", "navigate", "Open diff", null, emptyInput),
  command("ui.diff.toggle", "ui", "client", "navigate", "Toggle diff", null, emptyInput),
  command("ui.files.open", "ui", "client", "navigate", "Open files", null, emptyInput),
  command("ui.files.toggle", "ui", "client", "navigate", "Toggle file picker", null, emptyInput),
  command(
    "ui.project-search.toggle",
    "ui",
    "client",
    "navigate",
    "Toggle project search",
    null,
    emptyInput,
  ),
  command("ui.preview.open", "ui", "client", "navigate", "Open preview", null, emptyInput),
  command("ui.preview.toggle", "ui", "client", "navigate", "Toggle preview", null, emptyInput),
  command("ui.preview.refresh", "ui", "client", "navigate", "Refresh preview", null, emptyInput),
  command(
    "ui.preview.focus-url",
    "ui",
    "client",
    "navigate",
    "Focus preview URL",
    null,
    emptyInput,
  ),
  command("ui.preview.zoom-in", "ui", "client", "navigate", "Zoom preview in", null, emptyInput),
  command("ui.preview.zoom-out", "ui", "client", "navigate", "Zoom preview out", null, emptyInput),
  command(
    "ui.preview.reset-zoom",
    "ui",
    "client",
    "navigate",
    "Reset preview zoom",
    null,
    emptyInput,
  ),
  command("ui.terminal.open", "ui", "client", "navigate", "Open terminal", null, emptyInput),
  command("ui.terminal.toggle", "ui", "client", "navigate", "Toggle terminal", null, emptyInput),
  command("ui.right-panel.open", "ui", "client", "navigate", "Open right panel", null, emptyInput),
  command(
    "ui.right-panel.close",
    "ui",
    "client",
    "navigate",
    "Close right panel",
    null,
    emptyInput,
  ),
  command(
    "ui.right-panel.focus",
    "ui",
    "client",
    "navigate",
    "Focus right panel",
    null,
    emptyInput,
  ),
  command(
    "ui.right-panel.toggle",
    "ui",
    "client",
    "navigate",
    "Toggle right panel",
    null,
    emptyInput,
  ),
  command(
    "ui.editor.open-favorite",
    "ui",
    "client",
    "external",
    "Open favorite editor",
    null,
    emptyInput,
  ),
  command(
    "ui.external-url.open",
    "ui",
    "client",
    "external",
    "Open external URL",
    null,
    objectInput({ url: stringProperty }, ["url"]),
  ),
  command(
    "ui.model-picker.toggle",
    "ui",
    "client",
    "navigate",
    "Toggle model picker",
    null,
    emptyInput,
  ),
  ...([1, 2, 3, 4, 5, 6, 7, 8, 9] as const).map((index) =>
    command(
      `ui.model-picker.jump.${index}`,
      "ui",
      "client",
      "navigate",
      `Select model ${index}`,
      null,
      emptyInput,
    ),
  ),
  command(
    "ui.thread.previous",
    "ui",
    "client",
    "navigate",
    "Select previous thread",
    null,
    emptyInput,
  ),
  command("ui.thread.next", "ui", "client", "navigate", "Select next thread", null, emptyInput),
  ...([1, 2, 3, 4, 5, 6, 7, 8, 9] as const).map((index) =>
    command(
      `ui.thread.jump.${index}`,
      "ui",
      "client",
      "navigate",
      `Select recent thread ${index}`,
      null,
      emptyInput,
    ),
  ),
  command(
    "ui.app-view.open",
    "ui",
    "client",
    "navigate",
    "Open generated view",
    null,
    objectInput({ viewId: stringProperty }, ["viewId"]),
  ),

  command(
    "project.create",
    "project",
    "server",
    "mutate",
    "Create project",
    "project:mutate",
    objectInput(
      { projectId: stringProperty, title: stringProperty, workspaceRoot: stringProperty },
      ["projectId", "title", "workspaceRoot"],
    ),
  ),
  command(
    "project.clone",
    "project",
    "server",
    "external",
    "Clone project",
    null,
    objectInput({ remoteUrl: stringProperty, destinationPath: stringProperty }, [
      "remoteUrl",
      "destinationPath",
    ]),
  ),
  command(
    "project.add",
    "project",
    "server",
    "mutate",
    "Add project",
    "project:mutate",
    objectInput({ workspaceRoot: stringProperty, title: stringProperty }, ["workspaceRoot"]),
  ),
  command(
    "project.rename",
    "project",
    "server",
    "mutate",
    "Rename project",
    "project:mutate",
    objectInput({ projectId: stringProperty, title: stringProperty }, ["projectId", "title"]),
  ),
  command(
    "project.metadata.update",
    "project",
    "server",
    "mutate",
    "Update project metadata",
    "project:mutate",
    objectInput(
      { projectId: stringProperty, metadata: { type: "object", additionalProperties: true } },
      ["projectId", "metadata"],
    ),
  ),
  command(
    "project.action.upsert",
    "project",
    "server",
    "external",
    "Propose project action",
    null,
    objectInput(
      {
        projectId: stringProperty,
        action: {
          type: "object",
          properties: {
            id: stringProperty,
            name: stringProperty,
            icon: {
              type: "string",
              enum: [...PROJECT_CUSTOM_ACTION_ICON_IDS],
            },
            commandId: {
              type: "string",
              enum: ["ui.external-url.open", "script.run"],
            },
            url: stringProperty,
            scriptId: stringProperty,
          },
          required: ["id", "name", "commandId"],
          additionalProperties: false,
        },
      },
      ["projectId", "action"],
    ),
  ),
  command(
    "project.action.delete",
    "project",
    "server",
    "destructive",
    "Delete project URL action",
    null,
    objectInput({ projectId: stringProperty, actionId: stringProperty }, ["projectId", "actionId"]),
  ),
  command(
    "project.delete",
    "project",
    "server",
    "destructive",
    "Delete project",
    null,
    objectInput({ projectId: stringProperty, force: booleanProperty }, ["projectId"]),
  ),

  command(
    "thread.create",
    "thread",
    "server",
    "mutate",
    "Create thread",
    "thread:mutate",
    objectInput({ projectId: stringProperty, local: booleanProperty }),
  ),
  command(
    "thread.rename",
    "thread",
    "server",
    "mutate",
    "Rename thread",
    "thread:mutate",
    objectInput({ threadId: stringProperty, title: stringProperty }, ["threadId", "title"]),
  ),
  command(
    "thread.archive",
    "thread",
    "server",
    "mutate",
    "Archive thread",
    "thread:mutate",
    objectInput({ threadId: stringProperty }, ["threadId"]),
  ),
  command(
    "thread.unarchive",
    "thread",
    "server",
    "mutate",
    "Unarchive thread",
    "thread:mutate",
    objectInput({ threadId: stringProperty }, ["threadId"]),
  ),
  command(
    "thread.settle",
    "thread",
    "server",
    "mutate",
    "Settle thread",
    "thread:mutate",
    objectInput({ threadId: stringProperty }, ["threadId"]),
  ),
  command(
    "thread.unsettle",
    "thread",
    "server",
    "mutate",
    "Unsettle thread",
    "thread:mutate",
    objectInput({ threadId: stringProperty }, ["threadId"]),
  ),
  command(
    "thread.snooze",
    "thread",
    "server",
    "mutate",
    "Snooze thread",
    "thread:mutate",
    objectInput({ threadId: stringProperty, until: stringProperty }, ["threadId"]),
  ),
  command(
    "thread.unsnooze",
    "thread",
    "server",
    "mutate",
    "Unsnooze thread",
    "thread:mutate",
    objectInput({ threadId: stringProperty }, ["threadId"]),
  ),
  command(
    "thread.model.change",
    "thread",
    "server",
    "mutate",
    "Change thread model",
    "thread:mutate",
    objectInput(
      { threadId: stringProperty, modelSelection: { type: "object", additionalProperties: true } },
      ["threadId", "modelSelection"],
    ),
  ),
  command(
    "thread.mode.change",
    "thread",
    "server",
    "mutate",
    "Change thread mode",
    "thread:mutate",
    objectInput({ threadId: stringProperty, mode: stringProperty }, ["threadId", "mode"]),
  ),
  command(
    "thread.send",
    "thread",
    "server",
    "mutate",
    "Send thread message",
    "thread:mutate",
    objectInput({ threadId: stringProperty, text: stringProperty }, ["threadId", "text"]),
  ),
  command(
    "thread.interrupt",
    "thread",
    "server",
    "mutate",
    "Interrupt thread turn",
    "thread:mutate",
    objectInput({ threadId: stringProperty }, ["threadId"]),
  ),
  command(
    "thread.stop",
    "thread",
    "server",
    "mutate",
    "Stop thread turn",
    "thread:mutate",
    objectInput({ threadId: stringProperty }, ["threadId"]),
  ),
  command(
    "thread.checkpoint.revert",
    "thread",
    "server",
    "destructive",
    "Revert checkpoint",
    null,
    objectInput({ threadId: stringProperty, turnCount: integerProperty }, [
      "threadId",
      "turnCount",
    ]),
  ),
  command(
    "thread.delete",
    "thread",
    "server",
    "destructive",
    "Delete thread",
    null,
    objectInput({ threadId: stringProperty }, ["threadId"]),
  ),

  command(
    "delegation.thread.create",
    "delegation",
    "server",
    "mutate",
    "Create delegated thread",
    "assistant:delegate",
    objectInput({ projectId: stringProperty, title: stringProperty }, ["projectId"]),
  ),
  command(
    "delegation.turn.start",
    "delegation",
    "server",
    "mutate",
    "Start delegated turn",
    "assistant:delegate",
    objectInput({ threadId: stringProperty, text: stringProperty }, ["threadId", "text"]),
  ),
  command(
    "delegation.turn.stop",
    "delegation",
    "server",
    "mutate",
    "Stop delegated turn",
    "assistant:delegate",
    objectInput({ threadId: stringProperty }, ["threadId"]),
  ),
  command(
    "script.import",
    "script",
    "server",
    "external",
    "Save project terminal action",
    null,
    objectInput(
      {
        projectId: stringProperty,
        script: {
          type: "object",
          properties: {
            id: {
              type: "string",
              maxLength: 24,
              pattern: "^[a-z0-9][a-z0-9-]*$",
            },
            name: stringProperty,
            command: stringProperty,
            icon: {
              type: "string",
              enum: ["play", "test", "lint", "configure", "build", "debug"],
            },
            runOnWorktreeCreate: booleanProperty,
            previewUrl: stringProperty,
            autoOpenPreview: booleanProperty,
          },
          required: ["id", "name", "command"],
          additionalProperties: false,
        },
      },
      ["projectId", "script"],
    ),
  ),
  command(
    "script.run",
    "script",
    "client",
    "external",
    "Run imported project script",
    null,
    objectInput({ scriptId: stringProperty, commandHash: stringProperty }, ["scriptId"]),
  ),
  command("terminal.focus", "terminal", "client", "navigate", "Focus terminal", null, emptyInput),
  command("terminal.split", "terminal", "client", "navigate", "Split terminal", null, emptyInput),
  command(
    "terminal.split-vertical",
    "terminal",
    "client",
    "navigate",
    "Split terminal vertically",
    null,
    emptyInput,
  ),
  command("terminal.new", "terminal", "client", "navigate", "Create terminal", null, emptyInput),
  command(
    "terminal.close",
    "terminal",
    "client",
    "mutate",
    "Close terminal",
    "thread:mutate",
    emptyInput,
  ),
  command(
    "terminal.command.run",
    "terminal",
    "server",
    "external",
    "Run one-shot terminal command",
    null,
    objectInput({ command: stringProperty, cwd: stringProperty }, ["command"]),
  ),

  command(
    "source-control.refresh",
    "source-control",
    "server",
    "observe",
    "Refresh source control",
    null,
    emptyInput,
  ),
  command(
    "source-control.checkout",
    "source-control",
    "server",
    "external",
    "Checkout branch",
    null,
    objectInput({ branch: stringProperty }, ["branch"]),
  ),
  command(
    "source-control.publish",
    "source-control",
    "server",
    "external",
    "Publish branch",
    null,
    objectInput({ branch: stringProperty }, ["branch"]),
  ),
  command(
    "source-control.change-request.create",
    "source-control",
    "server",
    "external",
    "Create change request",
    null,
    objectInput({ title: stringProperty, body: stringProperty }, ["title"]),
  ),

  command(
    "settings.appearance.update",
    "settings",
    "client",
    "mutate",
    "Update appearance",
    "settings:ux",
    objectInput({ changes: { type: "object", additionalProperties: true } }, ["changes"]),
  ),
  command(
    "settings.ux.update",
    "settings",
    "client",
    "mutate",
    "Update UX settings",
    "settings:ux",
    objectInput({ changes: { type: "object", additionalProperties: true } }, ["changes"]),
  ),

  command(
    "view.present",
    "view",
    "client",
    "mutate",
    "Present generated view",
    "view:mutate",
    objectInput(
      {
        manifest: { type: "object", additionalProperties: true },
        createNew: { type: "boolean" },
      },
      ["manifest"],
    ),
  ),
  command(
    "view.update",
    "view",
    "client",
    "mutate",
    "Update generated view",
    "view:mutate",
    objectInput(
      {
        viewId: stringProperty,
        manifest: { type: "object", additionalProperties: true },
        expectedRevision: integerProperty,
      },
      ["viewId", "manifest", "expectedRevision"],
    ),
  ),
  command(
    "view.close",
    "view",
    "client",
    "mutate",
    "Close generated view",
    "view:mutate",
    objectInput({ viewId: stringProperty }, ["viewId"]),
  ),
  command(
    "view.pin",
    "view",
    "client",
    "mutate",
    "Pin generated view",
    "view:mutate",
    objectInput(
      {
        viewId: stringProperty,
        scope: { type: "string", enum: ["personal", "project"] },
        projectId: stringProperty,
      },
      ["viewId", "scope"],
    ),
  ),
  command(
    "view.unpin",
    "view",
    "client",
    "mutate",
    "Unpin generated view",
    "view:mutate",
    objectInput(
      {
        viewId: stringProperty,
        scope: { type: "string", enum: ["personal", "project"] },
        projectId: stringProperty,
      },
      ["viewId", "scope"],
    ),
  ),
  command(
    "view.delete",
    "view",
    "client",
    "destructive",
    "Delete generated view",
    null,
    objectInput({ viewId: stringProperty }, ["viewId"]),
  ),
] as const satisfies ReadonlyArray<AppCommandCatalogEntry>;

export type AppCommandId = (typeof APP_COMMAND_CATALOG)[number]["id"];

export const APP_COMMAND_IDS = APP_COMMAND_CATALOG.map(
  ({ id }) => id,
) as ReadonlyArray<AppCommandId>;

export function getAppCommandCatalogEntry(commandId: string): AppCommandCatalogEntry | undefined {
  return APP_COMMAND_CATALOG.find(({ id }) => id === commandId);
}

export function isAppCommandId(value: string): value is AppCommandId {
  return APP_COMMAND_IDS.includes(value as AppCommandId);
}

const KEYBINDING_APP_COMMAND_ALIASES = {
  "sidebar.toggle": "ui.sidebar.toggle",
  "assistant.toggle": "quick-chat.toggle",
  "quickChat.toggle": "quick-chat.toggle",
  "terminal.toggle": "ui.terminal.toggle",
  "terminal.split": "terminal.split",
  "terminal.splitVertical": "terminal.split-vertical",
  "terminal.new": "terminal.new",
  "terminal.close": "terminal.close",
  "rightPanel.toggle": "ui.right-panel.toggle",
  "diff.toggle": "ui.diff.toggle",
  "preview.toggle": "ui.preview.toggle",
  "preview.refresh": "ui.preview.refresh",
  "preview.focusUrl": "ui.preview.focus-url",
  "preview.zoomIn": "ui.preview.zoom-in",
  "preview.zoomOut": "ui.preview.zoom-out",
  "preview.resetZoom": "ui.preview.reset-zoom",
  "commandPalette.toggle": "ui.palette.toggle",
  "filePicker.toggle": "ui.files.toggle",
  "projectSearch.toggle": "ui.project-search.toggle",
  "composer.stash": "ui.composer.stash",
  "chat.new": "thread.create",
  "chat.newLocal": "thread.create",
  "editor.openFavorite": "ui.editor.open-favorite",
  "modelPicker.toggle": "ui.model-picker.toggle",
  "thread.previous": "ui.thread.previous",
  "thread.next": "ui.thread.next",
} as const satisfies Readonly<Record<string, AppCommandId>>;

export function appCommandIdForKeybinding(commandId: string): AppCommandId | null {
  if (commandId.startsWith("script.") && commandId.endsWith(".run")) return "script.run";
  const modelJump = /^modelPicker\.jump\.([1-9])$/.exec(commandId);
  if (modelJump) return `ui.model-picker.jump.${modelJump[1]}` as AppCommandId;
  const threadJump = /^thread\.jump\.([1-9])$/.exec(commandId);
  if (threadJump) return `ui.thread.jump.${threadJump[1]}` as AppCommandId;
  return (
    KEYBINDING_APP_COMMAND_ALIASES[commandId as keyof typeof KEYBINDING_APP_COMMAND_ALIASES] ?? null
  );
}
